## 1) คำสั่งใดใช้ติดตั้ง NumPy ในสภาพแวดล้อม Python ได้โดยตรง
A) conda import numpy			B) pip install numpy
C) python install numpy			D) import pip numpy


In [75]:
pip install numpy


# ตอบ B) pip install numpy

SyntaxError: invalid syntax (4285386258.py, line 1)

## 2) การนำเข้า NumPy ให้ใช้นามแฝงมาตรฐานว่า np ในข้อใด
A) import numpy				B) from numpy import as np
C) import numpy as np			D) from numpy import * as np



In [74]:
import numpy as np

# ตอบ C) import numpy as np

## 3) สำหรับอาเรย์ arr_2d = np.array([[1,5,2,0],[8,3,6,1],[1,7,2,9]]) ค่าของ arr_2d.shape คืออะไร
A) (4,3)						B) (3,4)
C) (12,)						D) (3,3)


In [73]:
arr_2d = np.array([[1,5,2,0],[8,3,6,1],[1,7,2,9]])
arr_2d.shape 

# ตอบ B) (3, 4)

(3, 4)

## 4) ให้ default_array = np.array([1,2,3,4,5,6]) ผลของ default_array[:3] คือข้อใดต่อไปนี้
A) [1,2,3]					B) [1,2,3,4]
C) [2,3,4]					D) [3,4,5]


In [72]:
default_array = np.array([1,2,3,4,5,6])
default_array[:3] 

# ตอบ A) [1, 2, 3]

array([1, 2, 3])

## 5) จากข้อเดิม ผลของ default_array[3:] คือ
A) [1,2,3]					B) [3,4,5]
C) [4,5,6]					D) [2,3,4,5,6]


In [71]:
import numpy as np

default_array = np.array([1, 2, 3, 4, 5, 6])
result = default_array[3:]
print(result) 

# ตอบ C) [4, 5, 6]


[4 5 6]


## 6) ให้ default_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่า default_array_2d[1,3] เท่ากับข้อใดต่อไปนี้
A) 6						B) 7
C) 8						D) 10


In [ ]:
default_array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
default_array_2d[1,3] 

# ตอบ C) 8

np.int64(8)

## 7) ให้ array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) ค่าของ array_attribute.ndim คือข้อใดต่อไปนี้
A) 1 						B) 2
C) 3						D) 4


In [69]:
array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array_attribute.ndim

# ตอบ B) 2

2

## 8) จากอาเรย์เดียวกัน array_attribute.size มีค่าเท่าใด
A) 7						B) 10
C) 12						D) 14


In [68]:
array_attribute = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array_attribute.size

# ตอบ C) 12

12

## 9) คำสั่งใดสร้างอาเรย์เลขคี่จาก 1 ถึง 15 ได้ถูกต้อง
A) np.arange(1,16,2)				B) np.arange(1,15,2)
C) np.arange(0,15,2)				D) np.arange(1,17,2)



In [67]:
np.arange(1,17,2)

# ตอบ A) np.arange(1, 16, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

## 10) np.arange(0,10,2) จะได้อาเรย์ยาวเท่าใด
A) 4						B) 5
C) 6						D) 1


In [66]:
np.arange(0,10,2) 

# ตอบ B) 5


array([0, 2, 4, 6, 8])

## 11) np.linspace(0,1,5) ค่าองค์ประกอบลำดับที่ 3 (index 2) คือข้อใดต่อไปนี้
A) 0.25						B) 0.5
C) 0.75						D) 1.0



In [65]:
import numpy as np
arr_lin = np.linspace(0, 1, 5)
print(arr_lin)

print(arr_lin[2])

# ตอบ B) 0.5


[0.   0.25 0.5  0.75 1.  ]
0.5


## 12) ข้อใด “ไม่ถูกต้อง” เกี่ยวกับฟังก์ชันสร้างอาเรย์
A) np.zeros((2,3)) สร้างอาเรย์ 2×3 เต็มไปด้วย 0	B) np.ones(5) สร้างอาเรย์ขนาด 5 เต็มไปด้วย 1
C) np.full((3,3),9) สร้างอาเรย์ 3×3 เต็มไปด้วย 9	D) np.arrang(4) สร้างอาเรย์ 0..3



In [ ]:
np.arrang(4)

# ตอบ D) np.arrang(4) สร้างอาเรย์ 0..3

AttributeError: module 'numpy' has no attribute 'arrang'

## 13) ให้ b = np.array([[1,1],[2,2]]) ผลของ b.sum(axis=0) คือข้อใดต่อไปนี้
A) [2,4]						B) [3,3]
C) 6						D) [1,2]



In [64]:
b = np.array([[1,1],[2,2]])
b.sum(axis=0) 

# ตอบ B) [3, 3]

array([3, 3])

## 14) ให้ arr = np.arange(12) ข้อใด “ถูกต้อง”
A) arr.reshape(3,5) ถูกต้อง			B) arr.reshape(6,2).shape == (2,6)
C) arr.reshape(6,2).T.shape == (2,6)		D) arr.reshape(4,4) ถูกต้อ


In [ ]:
arr.reshape(6,2).T.shape == (2,6)

# ตอบ C) arr.reshape(6,2).T.shape == (2,6)

True

## 15) ให้ a = np.ones((2,2)), b = np.zeros((2,2)) ผลของ np.vstack((a,b)).shape คือข้อใดต่อไปนี้
A) (2,4)						B) (4,2)
C) (2,2)						D) (1,4)



In [ ]:
import numpy as np
a = np.ones((2, 2))
b = np.zeros((2, 2))

c = np.vstack((a, b))

print("Shape of vstacked array:", c.shape)

# ตอบ B) (4,2)

Shape of vstacked array: (4, 2)


## 16) ให้ arr_split = np.arange(24).reshape(3,8) ผลของ np.hsplit(arr_split, 2) แต่ละชิ้นมี shape เป็นข้อใดต่อไปนี้
A) (3,2)						B) (3,4)
C) (1,8)						D) (8,3)


In [63]:
import numpy as np
arr_split = np.arange(24).reshape(3, 8)

split_arrays = np.hsplit(arr_split, 2)


print("Shape of the first split piece:", split_arrays[0].shape)



print("Shape of the second split piece:", split_arrays[1].shape)

# ตอบ B) (3,4)


Shape of the first split piece: (3, 4)
Shape of the second split piece: (3, 4)


## 17) ให้ a = np.arange(6); b = a.view(); b[0] = 99 ค่าของ a[0] จะเป็นเท่าใด
A) ไม่เปลี่ยน ยังเป็น 0				B) 99
C) เกิด Error					D) None



In [ ]:
a = np.arange(6); b = a.view(); b[0] = 99
a[0]

# ตอบ B) 99

np.int64(99)

## 18) ให้ arr = np.arange(12) ข้อใดตรงกับผล arr[[1,3,5]]
A) [1,3,5]					B) [0,1,2]
C) [2,4,6]					D) [1,4,7]


In [62]:
import numpy as np

arr = np.arange(12) 

result = arr[[1, 3, 5]]
print(result)

# ตอบ A) [1,3,5]


[1 3 5]


## 19) ให้ arr = np.arange(12) ผลของ arr[arr > 5] คือข้อใดต่อไปนี้
A) [6,7,8,9,10,11]				B) [5,6,7,8,9,10,11]
C) [0,1,2,3,4,5]					D) [7,8,9,10,11]



In [ ]:
import numpy as np

arr = np.arange(12) 
boolean_mask = arr > 5

result = arr[boolean_mask]

print(result)

# ตอบ A) [6,7,8,9,10,11]


[ 6  7  8  9 10 11]


## 20) ให้ data = np.array([1,2]), ones = np.ones(2) ผลของ data / ones คือข้อใดต่อไปนี้
A) [0,0]						B) [1.,2.]
C) Error เนื่องจากรูปทรงไม่ตรงกัน		D) [1,2,1,2]


In [ ]:
import numpy as np

data = np.array([1, 2])
ones = np.ones(2)

result = data / ones

print(result)

# ตอบ B) [1.,2.]


[1. 2.]


## 21) คำสั่งใดสร้าง DataFrame จากลิสต์ของลิสต์ได้ถูกต้อง
A) pd.DataFrame([1,2,3])			B) pd.DataFrame([[1,2,3],[4,5,6]])
C) pd.Series([[1,2,3],[4,5,6]])			D) pd.Table([[1,2,3],[4,5,6]])



In [ ]:
import pandas as pd

data = [[1, 2, 3], [4, 5, 6]]
df = pd.DataFrame(data)

print(df)

# ตอบ B) pd.DataFrame([[1,2,3],[4,5,6]])

   0  1  2
0  1  2  3
1  4  5  6


## 22) ต้องการกำหนดชื่อคอลัมน์เป็น ["A","B","C"] ตอนสร้าง DataFrame ใช้พารามิเตอร์ใด
A) names= 					B) cols= 
C) columns= 					D) header=



In [ ]:
import pandas as pd


data = [[1, 2, 3], [4, 5, 6]]
column_names = ["A", "B", "C"]
df = pd.DataFrame(data, columns=column_names)
print(column_names)

# ตอบ C) columns=

['A', 'B', 'C']


## 23) กำหนด index เองใน pd.DataFrame(..., index=[...]) มีผลอย่างไร
A) เปลี่ยนชนิดข้อมูล 				B) เปลี่ยนลำดับคอลัมน์ 
C) เปลี่ยน label ของแถว 			D) ไม่มีผล


In [61]:
import pandas as pd

data = {'col1': [10, 20], 'col2': [30, 40]}
row_labels = ['Row_A', 'Row_B']
df = pd.DataFrame(data, index=row_labels)

print(df)
# ตอบ C เปลี่ยน labelของแถว

       col1  col2
Row_A    10    30
Row_B    20    40


## 24) ฟังก์ชันใดใช้โหลดไฟล์ Excel
A) pd.read_table() 				B) pd.read_excel() 
C) pd.read_sas() 				D) pd.read_stata()


In [60]:
import pandas as pd
# df_excel = pd.read_excel("data/sales_data.xlsx") 
# print(df_excel.head())

#  ตอบ C) pd.read_excel(p, sheet_name='Sheet2')

# 25)ข้อใดต่อไปนี้อ่านชีตชื่อ "Sheet2" จาก Excel 
A) pd.read_excel(p, sheet="Sheet2")
B) pd.read_excel(p, sheetname="Sheet2")
C) pd.read_excel(p, sheet_name="Sheet2")
D) pd.read_excel(p).sheet("Sheet2")



In [59]:
import pandas as pd

# การอ่านชีตชื่อ "Sheet2"
# df = pd.read_excel(file_path, sheet_name='Sheet2')

# ตอบ C) pd.read_excel(p, sheet_name='Sheet2')

## 26) โหลด CSV จาก URL เป็น orders
A) orders = pd.read_csv("http://...")		B) orders = pd.DataFrame("http://...")
C) orders = pd.read_excel("http://...")		D) orders = pd.url_read("http://...")



In [ ]:
import pandas as pd

# orders = pd.read_csv(url)
# print(orders.head())

 #  ตอบ A) orders = pd.read_csv("http://...")

##   27) orders.info() ให้ข้อมูลหลักๆ อะไร
A) ค่าสถิติ mean/std ทุกคอลัมน์
B) รายชื่อคอลัมน์, Non-Null Count, Dtype, memory usage
C) ตัวอย่าง 5 แถวบน–ล่าง
D) กราฟค่าหายไป


In [42]:
# ตอบ B) รายชื่อคอลัมน์, Non-Null Count, Dtype, memory usage

## 28) ข้อใดต่อไปนี้เป็นวิธีดูรายชื่อคอลัมน์ทั้งหมดของ DataFrame ชื่อ orders
A) orders.colnames 				B) orders.headers 
C) orders.columns 				D) orders.names()



In [43]:
# ตอบ C) orders.columns

## 29) ข้อใดต่อไปนี้เป็นการเลือกคอลัมน์เดียว Country จาก DataFrame ชื่อ orders
A) orders.Country[ ]				B) orders["Country"]
C) orders[["Country","Country"]]		D) orders.loc["Country"]


In [ ]:
# ตอบ B) orders["Country"]

##  30) ข้อใดคือการเลือกหลายคอลัมน์ ['Customer','Country']
A) orders['Customer','Country']			B) orders[['Customer','Country']]
C) orders['Customer'][['Country']]			D) orders.loc['Customer','Country']


In [ ]:
# ตอบ B) orders[['Customer','Country']]

##  31) ข้อใดใช้ loc เลือกแถว 0–20 เฉพาะคอลัมน์ 'Category'
A) orders.loc[0,20,'Category']				B) orders.loc[0:20,'Category']
C) orders.iloc[0:20,'Category']				D) orders[0:20,'Category']



In [47]:
import pandas as pd
orders = pd.DataFrame({'Category': ['Electronics'] * 22})

result = orders.loc[0:20, 'Category']

print(f"Number of rows selected: {len(result)}")

# ตอบ B) orders.loc[0:20,'Category']


Number of rows selected: 21


##  32) ข้อใดต่อไปนี้เลือกแถว 10–30 เฉพาะคอลัมน์ ['OrderID','Quantity','Price','Paid']
A) orders.iloc[10:30, ['OrderID','Quantity','Price','Paid']]
B) orders.loc[10:30, ['OrderID','Quantity','Price','Paid']]
C) orders[10:30, ['OrderID','Quantity','Price','Paid']]
D) orders.loc[10:30, 'OrderID':'Paid'] (อาจกินคอลัมน์ที่ไม่ต้องการ)



In [49]:
import pandas as pd

data = {'OrderID': range(100, 140), 'Quantity': [1]*40, 'Price': [50.0]*40, 'Paid': ['Yes']*40}
orders = pd.DataFrame(data)

selected_data = orders.loc[10:30, ['OrderID','Quantity','Price','Paid']]


print(f"Shape of selected data: {selected_data.shape}")

# ตอบ B) orders.loc[10:30, ['OrderID','Quantity','Price','Paid']]


Shape of selected data: (21, 4)


## 33) ข้อใดต่อไปนี้กรองแถวที่ Quantity > 5 ให้ได้ DataFrame
A) orders["Quantity"] > 5				B) orders[orders["Quantity"] > 5]
C) orders.loc["Quantity"] > 5				D) orders.filter("Quantity > 5")


In [50]:
import pandas as pd

data = {'OrderID': [100, 101, 102, 103], 'Quantity': [2, 7, 5, 9]}
orders = pd.DataFrame(data)

filtered_orders = orders[orders["Quantity"] > 5]

print(filtered_orders)

# ตอบ B) orders[orders["Quantity"] > 5]

   OrderID  Quantity
1      101         7
3      103         9


##  34) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึง
Quantity > 3 และ Country == 'Thailand'
A) orders[orders["Quantity"] > 3 and orders["Country"] == "Thailand"]
B) orders[(orders["Quantity"] > 3) & (orders["Country"] == "Thailand")]
C) orders.query(Quantity > 3 & Country == 'Thailand') (ต้องเป็นสตริง)
D) orders[(orders["Quantity"] > 3) && (orders["Country"] == "Thailand")]



In [51]:
import pandas as pd

data = {'Country': ['Thailand', 'USA', 'Thailand', 'Japan'], 'Quantity': [5, 2, 4, 6]}
orders = pd.DataFrame(data)

cond_and = (orders["Quantity"] > 3) & (orders["Country"] == "Thailand")
filtered_orders = orders[cond_and]

print(filtered_orders)


# ตอบ B) orders[(orders["Quantity"] > 3) & (orders["Country"] == "Thailand")]

    Country  Quantity
0  Thailand         5
2  Thailand         4


##  35) ข้อใดต่อไปนี้เป็นการใช้เงื่อนไขหลายเงื่อนไขที่แสดงถึงเงื่อนไข OR
เลือก Category == 'Electronics' หรือ Paid == 'No'
A) orders[(orders["Category"] == "Electronics") || (orders["Paid"] == "No")]
B) orders[(orders["Category"] = "Electronics") | (orders["Paid"] == "No")]
C) orders[(orders["Category"] == "Electronics") | (orders["Paid"] == "No")]
D) orders["Category"].or(orders["Paid"] == "No")



In [52]:
import pandas as pd
data = {'Category': ['Electronics', 'Fashion', 'Electronics', 'Books'], 
        'Paid': ['Yes', 'Yes', 'No', 'No']}
orders = pd.DataFrame(data)


cond_or = (orders["Category"] == "Electronics") | (orders["Paid"] == "No")
filtered_orders = orders[cond_or]


print(filtered_orders)


# ตอบ C) orders[(orders["Category"] == "Electronics") | (orders["Paid"] == "No")]

      Category Paid
0  Electronics  Yes
2  Electronics   No
3        Books   No


##  36) ข้อใดต่อไปนี้ใช้ isin: เลือกประเทศเฉพาะ ['Thailand','Japan','USA']
A) orders[orders["Country"] in ['Thailand','Japan','USA']]
B) orders[orders["Country"].isin(['Thailand','Japan','USA'])]
C) orders.isin(orders["Country"], ['Thailand','Japan','USA'])
D) orders["Country"].isin(['Thailand','Japan','USA']) (ยังไม่ได้ slice)


In [53]:
import pandas as pd

data = {'Country': ['Thailand', 'USA', 'Germany', 'Japan', 'France']}
orders = pd.DataFrame(data)

allowed_countries = ['Thailand', 'Japan', 'USA']
filtered_orders = orders[orders["Country"].isin(allowed_countries)]


print(filtered_orders)


# ตอบ B) orders[orders["Country"].isin(['Thailand','Japan','USA'])]

    Country
0  Thailand
1       USA
3     Japan


##  37) ข้อใดต่อไปนี้ใช้ query กรองออเดอร์หมวด Fashion และราคามากกว่า 1000
A) orders.query("Category == 'Fashion' and Price > 1000")
B) orders.query(Category == 'Fashion' and Price > 1000)
C) orders.query('Category' == 'Fashion' and 'Price' > 1000)
D) orders.query("Category = 'Fashion' & Price > 1000")


In [54]:
import pandas as pd

data = {'Category': ['Fashion', 'Electronics', 'Fashion', 'Fashion'], 
        'Price': [1500, 800, 500, 1200]}
orders = pd.DataFrame(data)


filtered_orders = orders.query("Category == 'Fashion' and Price > 1000")


print(filtered_orders)

# ตอบ A) orders.query("Category == 'Fashion' and Price > 1000")

  Category  Price
0  Fashion   1500
3  Fashion   1200


##  38) ข้อใดต่อไปนี้เพิ่มคอลัมน์คงที่และคอลัมน์คำนวณ (เช่น Total = Quantity*Price)
A)
orders['Shop'] = 'Bangkok'
orders['Total'] = orders['Quantity'] * orders['Price']
B)
orders.add_column('Shop','Bangkok')
orders.add_column('Total', orders['Quantity'] * orders['Price'])
C)
orders['Shop'] == 'Bangkok'
orders['Total'] == orders['Quantity'] * orders['Price']
D)
orders.Shop = 'Bangkok'
orders.Total = orders.Quantity multiply orders.Price


In [56]:
# ตอบ A orders['Shop'] = 'Bangkok'
# orders['Total'] = orders['Quantity'] * orders['Price']


##  39) ข้อใดต่อไปนี้เป็นการลบหลายคอลัมน์ด้วย drop 
A) orders = orders.drop('Paid','Category')
B) orders = orders.drop(columns=['Paid','Category'])
C) orders.drop(columns=['Paid','Category']) (inplace=True)
D) orders.remove(columns=['Paid','Category'])



In [57]:
import pandas as pd

data = {'OrderID': [1, 2], 'Paid': ['Yes', 'No'], 'Category': ['A', 'B'], 'Price': [10, 20]}
orders = pd.DataFrame(data)
print("Before drop:\n", orders)

orders = orders.drop(columns=['Paid', 'Category'])


print("\nAfter drop:\n", orders)

# ตอบ B) orders = orders.drop(columns=['Paid','Category'])

Before drop:
    OrderID Paid Category  Price
0        1  Yes        A     10
1        2   No        B     20

After drop:
    OrderID  Price
0        1     10
1        2     20


##  40) ข้อใดต่อไปนี้ เรียงลำดับตาม Country และรองลงมาด้วย Price จากน้อยไปมาก
A) orders.order_by(['Country','Price'])
B) orders.sort_values(['Country','Price'], ascending=[True,True])
C) orders.sort(['Country','Price'])
D) orders.sort_index(['Country','Price'])



In [58]:
import pandas as pd


data = {'Country': ['USA', 'Thailand', 'Thailand', 'USA', 'Japan'], 
        'Price': [500, 1000, 500, 100, 1000]}
orders = pd.DataFrame(data)


sorted_df = orders.sort_values(['Country', 'Price'], ascending=[True, True])

print(sorted_df)
 # ตอบ B) orders.sort_values(['Country','Price'], ascending=[True,True])

    Country  Price
4     Japan   1000
2  Thailand    500
1  Thailand   1000
3       USA    100
0       USA    500
