## 1. สร้างอาเรย์ 1 มิติ ที่มีค่าเป็นเลขคี่จาก 1 ถึง 15 โดยใช้ np.arange()

In [1]:
import numpy as np

array_1d = np.arange(1, 16, 2)  # เริ่มที่ 1 ถึง 15 โดยเพิ่มทีละ 2 (เลขคี่)
print("1D array (เลขคี่):", array_1d)

1D array (เลขคี่): [ 1  3  5  7  9 11 13 15]


## 2. สร้างอาเรย์ 2 มิติ ขนาด 3 แถว 5 คอลัมน์ ที่มีค่าเริ่มต้นเป็น 9

In [2]:
array_2d = np.full((3, 5), 9)  # สร้าง array ขนาด 3x5 ที่มีค่าเป็น 9
print("2D array (ค่าเป็น 9):\n", array_2d)

2D array (ค่าเป็น 9):
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


##  3. สร้างอาเรย์ 3 มิติ ขนาด 2 × 3 × 4 ที่มีค่าเป็น 0 โดยใช้ np.zeros() และตรวจสอบ shape

In [3]:
array_3d = np.zeros((2, 3, 4))  # สร้าง array ขนาด 2x3x4 ที่มีค่าเป็น 0
print("3D array (ค่าเป็น 0):\n", array_3d)
print("Shape ของ 3D array:", array_3d.shape)

3D array (ค่าเป็น 0):
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape ของ 3D array: (2, 3, 4)


##  4. ใช้ np.linspace() เพื่อสร้างอาเรย์ที่มี 10 ค่า กระจายจาก 0 ถึง 5 แบบช่วงเท่ากัน

In [4]:
array_linspace = np.linspace(0, 5, 10)  # เริ่มจาก 0 ถึง 5 มี 10 ค่า
print("Array จาก linspace:\n", array_linspace)

Array จาก linspace:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## แบบฝึกหัด: NumPy Indexing & Slicing default_array = np.array([1,2,3,4,5,6]) default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12]

In [6]:
import numpy as np

# สร้างอาเรย์ต้นฉบับ
default_array = np.array([1, 2, 3, 4, 5, 6])
default_array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

##  1. เลือกสมาชิกตัวสุดท้ายของ default_array

In [7]:
last_item = default_array[-1]
print("last_item:", last_item)

last_item: 6


##  2. เลือกสมาชิกตั้งแต่ตำแหน่งที่ 2 ถึง 4 (index 1 ถึง 3)

In [8]:
slice_2_to_4 = default_array[1:4]
print("slice_2_to_4:", slice_2_to_4)

slice_2_to_4: [2 3 4]


##  3. เลือกค่าทั้งหมดในคอลัมน์ที่ 2 ของ default_array_2d

In [9]:
column_2 = default_array_2d[:, 1]
print("column_2:", column_2)

column_2: [ 2  6 10]


## 4. เลือกค่าในแถวแรก 2 ตัวสุดท้าย ของ default_array_2d


In [10]:
row1_last2 = default_array_2d[0, -2:]
print("row1_last2:", row1_last2)

row1_last2: [3 4]


##  5. เลือกค่าที่อยู่มุมขวาล่าง (แถวสุดท้าย คอลัมน์สุดท้าย)

In [11]:
bottom_right = default_array_2d[-1, -1]
print("bottom_right:", bottom_right)

bottom_right: 12


## แบบฝึกหัด 3:

คำนวณ (x^2 + 2x) เมื่อ x = [1,2,3,4]

In [12]:
import numpy as np

x = np.array([1, 2, 3, 4])
result = x**2 + 2*x

print("ผลลัพธ์ของ x^2 + 2x:", result)

ผลลัพธ์ของ x^2 + 2x: [ 3  8 15 24]
