## 1. import numpy as np เรียกใช้งาน numpy

In [1]:
import numpy as np

In [5]:
# syntax creating arr
# arr_name = np.arr(1)


# 1 - dimensiona1 array 1,5,2,0 
arr_1d = np.array([ 1, 5, 2, 0 ])
# 2 - dimensional array  1,5,2,0  8,3,6,1  1,7,2,9
arr_2d = np.array([ [1,5,2,0], [8,3,6,1], [1,7,2,9] ])

# 3 - dimensional array 10, 15, 20, 25   30, 35, 40, 45   50, 55, 60, 65 
arr_3d = np.array([ [10, 15], 
                [ 20, 25], 
                
                [30, 35], 
                [40, 45],
                
                [50, 55], 
                [60, 65] ])


In [11]:
print (arr_1d)
print ('......')
print (arr_2d)
print ('......')
print (arr_3d)

[1 5 2 0]
......
[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]
......
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]]


In [12]:
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [16]:
# สามตัวแรก จาก default_array
# default_array[ :3]

# ตัวที่ 4 เป็นต้นไป 
# default_array[3:]

# สมาชิกใน row 2 columns 4 
default_array_2d[1,3]

np.int64(8)

In [18]:
array_attribute = np.array([ [  1, 2, 3, 4 ], [  5, 6, 7, 8 ], [ 9, 10, 11, 12 ] ])

In [27]:
#ตรวจสอบคุณสมบัติของarr


# array_attribute.ndim ดูว่ามีกี่มิติ
# array_attribute.ndim
# array_attribute.shape ดูว่ามีกี่แถวกี่คอลัมน์
# array_attribute.shape
# array_attribute.size จำนวนสมาชิก
# array_attribute.size
# array_attribute.dtype ตรวจสอบชนิดข้อมูล
array_attribute.dtype


dtype('int64')

In [30]:
zero_2d_array = np.zeros(2)
one_1d_array = np.ones(5)
arange_array = np.arange(4)
step_arange_array= np.arange(2,9,2)  # start stop step 

In [34]:
print(zero_2d_array)
print(one_1d_array)
print(arange_array)
print(step_arange_array)

[0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3]
[2 4 6 8]


In [36]:
data = np.array([ 1, 2])
ones = np.ones(2)# [1, 1 ]
b = np.array([ [1,1], [2,2] ])  
# [ 1, 1 ]  
# [ 2, 2 ]

In [37]:
sum = data + ones  
diff = data - ones 
multiply_array = data * ones 
divide_array = data/ones
col_sum = b.sum(axis=0) # ผลรวมแนว column
row_sum= b.sum(axis=1) # ผลรวมแนว row 

In [38]:
sum
diff
multiply_array
divide_array
# print(col_sum)  
print(row_sum)

[2 4]


In [39]:
# np.set_printoptions(precision, suppress)  
# precision: dataType:int default: 8  กำหนดทศนิยม 
# suppress:  dataType: Bool default: False  แสดงผลในรูปแบบวิทยาศาสตร์  True จะกำหนดให้ใช้ ทศนิยม 

np.set_printoptions()  
# np.set_printoptions(precision=2, suppress=True)  
arr = np.random.rand(4,4)
print(arr)

[[0.75879173 0.87103277 0.31193526 0.54841943]
 [0.63241477 0.48155434 0.49472161 0.46648236]
 [0.99850095 0.83424377 0.12663586 0.64397072]
 [0.91092693 0.16268498 0.68297512 0.55207992]]


In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a + b =", a + b)
print("a * 10 =", a * 10)
print("a ** 2 =", a ** 2)
print("b/2", b/2)

a + b = [5 7 9]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]
b/2 [2.  2.5 3. ]


In [41]:
# a + b 
print("a + b =", a + b)
# a * 10 
print("a * 10 =", a * 10)
# a^2
print("a ** 2 =", a ** 2)
# b / 2 
print("b/2", b/2)

a + b = [5 7 9]
a * 10 = [10 20 30]
a ** 2 = [1 4 9]
b/2 [2.  2.5 3. ]


In [42]:
a = np.arange(10)
b = np.array([[1,2,3],[4,5,6]])
print("a: ", a)
print("b: ",b)   # print("b: \n",b)  

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [[1 2 3]
 [4 5 6]]


In [43]:
# Slice array index:2 to index: 6  [2,3,4,5,6]
print(a[2:7])  # slice
# slice row 
for row in b:
    print(row)

[2 3 4 5 6]
[1 2 3]
[4 5 6]


In [45]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [49]:
array_sample = np.arange(20)

In [54]:
#reshapr สองแถว
array_sample.reshape(2,10)
#reshapr 10แถว
array_sample.reshape(10,2)
#reshapr2แถว3หลัก
array_sample.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])